import { Metadata } from 'next';
import { SITE_CONFIG } from '@/lib/constants';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms and conditions for using AB Entertainment services and website.',
};

export default function TermsPage() {
  return (
    <section className="min-h-screen bg-[#062434] py-16 sm:py-24">
      <div className="container-eu max-w-4xl">
        <h1 className="text-4xl sm:text-5xl font-display font-bold text-[#CC8A1C] mb-4">
          Terms of Service
        </h1>
        <p className="text-[#7E7180] text-sm font-body mb-12">
          Last updated: 28 March 2026
        </p>

        <div className="prose prose-invert max-w-none space-y-8">
          <section className="border-l-4 border-[#CC8A1C] pl-6">
            <h2 className="text-2xl font-display text-[#CC8A1C] mb-4">1. Acceptance of Terms</h2>
            <p className="text-[white] font-body leading-relaxed">
              By accessing or using the {SITE_CONFIG.name} website and services, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services. These terms are governed by the laws of Victoria, Australia.
            </p>
          </section>

          <section className="border-l-4 border-[#CC8A1C] pl-6">
            <h2 className="text-2xl font-display text-[#CC8A1C] mb-4">2. Services</h2>
            <p className="text-[white] font-body leading-relaxed">
              {SITE_CONFIG.name} provides cultural event management, ticketing, and related entertainment services in Melbourne, Australia. Our digital platform offers event browsing, ticket purchasing, newsletter subscriptions, and an AI concierge for event inquiries.
            </p>
          </section>

          <section className="border-l-4 border-[#CC8A1C] pl-6">
            <h2 className="text-2xl font-display text-[#CC8A1C] mb-4">3. Ticket Purchases and Refunds</h2>
            <p className="text-[white] font-body leading-relaxed mb-3">
              All ticket purchases are subject to availability. Prices are displayed in Australian Dollars (AUD) and include GST where applicable.
            </p>
            <p className="text-[white] font-body leading-relaxed">
              Refund requests must be submitted at least 7 days prior to the event date. Refunds will be processed to the original payment method within 10 business days. Event cancellations by {SITE_CONFIG.name} will result in a full refund. Venue changes do not automatically qualify for a refund.
            </p>
          </section>

          <section className="border-l-4 border-[#CC8A1C] pl-6">
            <h2 className="text-2xl font-display text-[#CC8A1C] mb-4">4. User Conduct</h2>
            <p className="text-[white] font-body leading-relaxed">
              You agree not to misuse our services, including but not limited to: attempting to circumvent security measures, submitting false information, engaging in automated data collection without authorisation, or using the platform for any unlawful purpose. We reserve the right to suspend or terminate access for violations.
            </p>
          </section>

          <section className="border-l-4 border-[#CC8A1C] pl-6">
            <h2 className="text-2xl font-display text-[#CC8A1C] mb-4">5. Intellectual Property</h2>
            <p className="text-[white] font-body leading-relaxed">
              All content on this website — including text, graphics, logos, images, audio, video, and software — is the property of {SITE_CONFIG.name} or its content suppliers and is protected by Australian and international copyright laws. You may not reproduce, distribute, or create derivative works without written permission.
            </p>
          </section>

          <section className="border-l-4 border-[#CC8A1C] pl-6">
            <h2 className="text-2xl font-display text-[#CC8A1C] mb-4">6. AI Concierge</h2>
            <p className="text-[white] font-body leading-relaxed">
              Our AI concierge provides general event information and assistance. Responses are generated by artificial intelligence and may not always be accurate. The AI concierge does not constitute professional advice, and booking or payment commitments should be confirmed through our official channels.
            </p>
          </section>

          <section className="border-l-4 border-[#CC8A1C] pl-6">
            <h2 className="text-2xl font-display text-[#CC8A1C] mb-4">7. Limitation of Liability</h2>
            <p className="text-[white] font-body leading-relaxed">
              To the maximum extent permitted by Australian Consumer Law, {SITE_CONFIG.name} shall not be liable for any indirect, incidental, special, or consequential damages arising from the use of our services. Our total liability shall not exceed the amount paid for the specific service in question.
            </p>
          </section>

          <section className="border-l-4 border-[#CC8A1C] pl-6">
            <h2 className="text-2xl font-display text-[#CC8A1C] mb-4">8. Changes to Terms</h2>
            <p className="text-[white] font-body leading-relaxed">
              We reserve the right to update these terms at any time. Changes will be posted on this page with an updated revision date. Continued use of our services after changes constitutes acceptance of the revised terms.
            </p>
          </section>

          <section className="border-l-4 border-[#CC8A1C] pl-6">
            <h2 className="text-2xl font-display text-[#CC8A1C] mb-4">9. Contact</h2>
            <p className="text-[white] font-body leading-relaxed">
              For questions about these terms, please contact:
            </p>
            <address className="not-italic text-[white] font-body mt-4 leading-relaxed">
              <strong className="text-[#CC8A1C]">{SITE_CONFIG.name}</strong>
              <br />
              Email:{' '}
              <a href={`mailto:${SITE_CONFIG.contact.email}`} className="text-[#CC8A1C] hover:underline">
                {SITE_CONFIG.contact.email}
              </a>
              <br />
              Phone:{' '}
              <a href={`tel:${SITE_CONFIG.contact.phone}`} className="text-[#CC8A1C] hover:underline">
                {SITE_CONFIG.contact.phone}
              </a>
            </address>
          </section>
        </div>
      </div>
    </section>
  );
}
